/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.com.weimont.cafeteriawmj_s3.view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author montespierreg
 */
public class CafeteriaMain extends javax.swing.JFrame {

    /**
     * Creates new form CafeteriaMain
     */
    public CafeteriaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        menuProceso = new javax.swing.JMenu();
        menuProcesoArticulos = new javax.swing.JMenu();
        menuProcesoArticulosNuevo = new javax.swing.JMenuItem();
        menuProcesoEmpleados = new javax.swing.JMenu();
        menuProcesoEmpleadosNuevo = new javax.swing.JMenuItem();
        menuProcesoVentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        menuBar.add(fileMenu);

        menuProceso.setText("Procesos");

        menuProcesoArticulos.setText("Articulos");

        menuProcesoArticulosNuevo.setText("Nuevo");
        menuProcesoArticulos.add(menuProcesoArticulosNuevo);

        menuProceso.add(menuProcesoArticulos);

        menuProcesoEmpleados.setText("Empleados");

        menuProcesoEmpleadosNuevo.setText("Nuevo");
        menuProcesoEmpleadosNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoEmpleadosNuevoActionPerformed(evt);
            }
        });
        menuProcesoEmpleados.add(menuProcesoEmpleadosNuevo);

        menuProceso.add(menuProcesoEmpleados);

        menuProcesoVentas.setText("Ventas");
        menuProceso.add(menuProcesoVentas);

        menuBar.add(menuProceso);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProcesoEmpleadosNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoEmpleadosNuevoActionPerformed
        try {
            JInternalFrame view = new VendedorNuevoView();
            desktopPane.add(view);
            view.setVisible(true);
            view.setMaximum(true);
        } catch (PropertyVetoException ex) {
            
        }
    }//GEN-LAST:event_menuProcesoEmpleadosNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeteriaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeteriaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeteriaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeteriaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeteriaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuProceso;
    private javax.swing.JMenu menuProcesoArticulos;
    private javax.swing.JMenuItem menuProcesoArticulosNuevo;
    private javax.swing.JMenu menuProcesoEmpleados;
    private javax.swing.JMenuItem menuProcesoEmpleadosNuevo;
    private javax.swing.JMenu menuProcesoVentas;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
