/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.com.weimont.cafeteriawmj_s3.view;



import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import pe.com.weimont.cafeteriawmj_s3.db.AccesoDB;
import pe.com.weimont.cafeteriawmj_s3.model_dto.ItemConsVenta;
import pe.com.weimont.cafeteriawmj_s3.model_dto.ItemDetVenta;
import pe.com.weimont.cafeteriawmj_s3.model_dto.SessionConsV_v3;
import pe.com.weimont.cafeteriawmj_s3.model_dto.SessionDetV_v31;
import pe.com.weimont.cafeteriawmj_s3.service.VentaService;


/**
 *
 * @author montespierreg
 */
public class NuevaVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaVenta
     */
    public NuevaVenta() {
        initComponents();
        
        /////////////////////
        VentaService venta1 = new VentaService();
        //ItemConsVenta ventaCons21 = new ItemConsVenta(3, 2, 111,1111, 0, 0, 0, 0);
        
        //lblIdVenta.setText("" + ventaCons21.getIdVenta());
        //lblSubTotal.setText("" + ventaCons21.getSubTotal());
        //lblImporTotal.setText(""+ ventaCons21.getImporTotal());
        //lblUnidTotales.setText("" + ventaCons21.getUnidTotales());
        //lblIgv.setText("" + ventaCons21.getIgv());
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdVenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUnidTotales = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblIgv = new javax.swing.JLabel();
        lblImporTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        jLabel1.setText("idVenta:");

        lblIdVenta.setText("lblIdVenta");

        jLabel2.setText("Nueva Venta");

        jLabel3.setText("unidTotales:");

        jLabel4.setText("subTotal:");

        jLabel5.setText("igv");

        jLabel6.setText("imporTotal");

        lblUnidTotales.setText("lblUnidTotales");

        lblSubTotal.setText("lblSubTotal");

        lblIgv.setText("lblIgv");

        lblImporTotal.setText("lblImporTotal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIdVenta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUnidTotales)))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSubTotal)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImporTotal))
                            .addComponent(lblIgv))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdVenta)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(lblSubTotal)
                    .addComponent(lblImporTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lblUnidTotales)
                    .addComponent(lblIgv))
                .addContainerGap())
        );

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idDetVenta	", "idArticulo", "cant", "precioUnit", "importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ACCIONES"));

        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMenu.setText("Regresar");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnMenu)
                        .addComponent(btnActualizar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
  
        try {
            JFrame view = new NuevaVentaNuevoItem();
            view.setVisible(true);
            //view.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //////////////////////////////////////
        //Obtener numero de idVenta
        Connection cn2 = null;
        int idv=1;
        
        try {
            cn2 = AccesoDB.getConnection();  
            cn2.setAutoCommit(false);
            Statement stm = cn2.createStatement();
            String sql = "select count(*) from ventas";
            //SELECT COUNT(*) FROM `ventas` 
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                int count = rs.getInt("count(*)");
                
                idv = count + 1;
                //int idVenta2 = count;
            }
            
            
            rs.close();
            stm.close();
            System.out.println("ok");
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            try {
                cn2.close();
            } catch (Exception e) {
            }
        }
        
        //////////////////////////////////////
        ///////////////////////////////////////
        
        //Actualizar tabla por total de detallados de venta
        
        DefaultTableModel tabla;
        
        tabla = (DefaultTableModel)tblResultado.getModel();
        tabla.setRowCount(0);
        
        
        int n = 1;
        
        while(n<=SessionDetV_v31.r){
            Object[] rowData = {
                SessionDetV_v31.get(n).getIdDet_Venta(),
                SessionDetV_v31.get(n).getIdArticulo(),
                SessionDetV_v31.get(n).getCant(),
                SessionDetV_v31.get(n).getPrecioUnit(),
                SessionDetV_v31.get(n).getImporte()
            };
            tabla.addRow(rowData);
            n = n + 1;
        }
        
        //////////////////////////////////////////////////
    
        //Actualizar consolidado de ventas
        
        int idVenta = idv;//no
        int idEmpleado =1;//no
        long fechaVenta =11111;//no
        long horaVenta =11111;//no
        int unidTotales = 0;
        double subTotal = 0;
        double igv=0;
        double imporTotal=0;
        
        n = 1;
        
        while(n<=SessionDetV_v31.r){
                SessionDetV_v31.get(n).getIdDet_Venta();
                SessionDetV_v31.get(n).getIdArticulo();
                unidTotales = unidTotales + SessionDetV_v31.get(n).getCant();
                subTotal = subTotal + SessionDetV_v31.get(n).getPrecioUnit() * SessionDetV_v31.get(n).getCant();
                
                
            n = n + 1;
        }
        igv = 0.18*subTotal;
        imporTotal = 1.18*subTotal;
        
        ItemConsVenta ventaCons21 = new ItemConsVenta(idVenta, idEmpleado, fechaVenta, horaVenta, unidTotales, subTotal, igv, imporTotal);
        SessionConsV_v3.put(1, ventaCons21);
        lblIdVenta.setText("" + Integer.toString(idVenta));
        lblSubTotal.setText("" + Double.toString(subTotal));
        lblImporTotal.setText(""+ Double.toString(imporTotal));
        lblUnidTotales.setText("" + Integer.toString(unidTotales));
        lblIgv.setText("" + Double.toString(igv));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        
        //////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////

        // Guardar ConsVenta y DetVenta
        ItemConsVenta ventaCons = SessionConsV_v3.get(1);
        
        
        //Insertar Consolidado de Venta
        Connection cn = null;
    
        try {
            
            
                cn = AccesoDB.getConnection();  
                cn.setAutoCommit(false);
                //Statement stm = cn.createStatement();
            
                
                String sql = "insert into ventas(idVenta, idEmpleado, fechaVenta, " +
                            "horaVenta, unidTotales, subTotal, igv, imporTotal) "
                        + "values(?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstm = cn.prepareStatement(sql);
            
                pstm.setString(1, Integer.toString(ventaCons.getIdVenta()));
                pstm.setString(2, Integer.toString(ventaCons.getIdEmpleado()));
                pstm.setString(3, Long.toString(ventaCons.getFechaVenta()));
                pstm.setString(4, Long.toString(ventaCons.getHoraVenta()));
                pstm.setString(5, Integer.toString(ventaCons.getUnidTotales()));
                pstm.setString(6, Double.toString(ventaCons.getSubTotal()));
                pstm.setString(7, Double.toString(ventaCons.getIgv()));
                pstm.setString(8, Double.toString(ventaCons.getImporTotal()));

                pstm.executeUpdate();
                cn.commit();
                
                System.out.println("Datos insertados");
                

            
        } catch (Exception e) {
            e.printStackTrace();
            try {
                cn.rollback();
            } catch (Exception e1) {
            }
        }finally{
            try {
                cn.close();
            } catch (Exception e) {
            }
        }
        
        //////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        //VentaService.contador = 0; // ver si se borra
        //SessionDetV_v31.put(1, null);// ver si se borra
        //SessionDetV_v31.put(2, null);// ver si se borra
        //SessionDetV_v31.put(3, null);// ver si se borra
        //SessionDetV_v31.put(4, null);// ver si se borra
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdVenta;
    private javax.swing.JLabel lblIgv;
    private javax.swing.JLabel lblImporTotal;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblUnidTotales;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
